### ISSUE TITLE
Cannot compile in Ubuntu 22.04 - error: reference to ‘size’ is ambiguous

### ISSUE THREAD

**Issue by andimik** [newspaperman/bbframe-tools#4]
In latest Ubuntu 22.04 compilation fails 

```
$ make
g++ -o pts2bbf pts2bbf.cpp
pts2bbf.cpp: In function ‘int main(int, char**)’:
pts2bbf.cpp:15:9: error: reference to ‘size’ is ambiguous
   15 |         size=200;
      |         ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from pts2bbf.cpp:1:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
pts2bbf.cpp:10:5: note:                 ‘int size’
   10 | int size;
      |     ^~~~
pts2bbf.cpp:16:33: error: reference to ‘size’ is ambiguous
   16 |         char* packets= new char[size*188];
      |                                 ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from pts2bbf.cpp:1:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
pts2bbf.cpp:10:5: note:                 ‘int size’
   10 | int size;
      |     ^~~~
pts2bbf.cpp:18:37: error: reference to ‘size’ is ambiguous
   18 |                 inbuf->read(packets,size * 188);
      |                                     ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from pts2bbf.cpp:1:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
pts2bbf.cpp:10:5: note:                 ‘int size’
   10 | int size;
      |     ^~~~
pts2bbf.cpp:21:32: error: reference to ‘size’ is ambiguous
   21 |                 for(int i=0; i<size*188;i+=188) {
      |                                ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from pts2bbf.cpp:1:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
pts2bbf.cpp:10:5: note:                 ‘int size’
   10 | int size;
      |     ^~~~
make: *** [Makefile:10: pts2bbf] Fehler 1
```

```
$ c++ --version
c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by andimik** [comment]
`make -k` or `make -i` say then:

```
cc -o bbfudpdecap bbfudpdecap.cpp
/usr/bin/ld: /tmp/cc6hpoSz.o: warning: relocation against `_ZSt4cout' in read-only section `.text'
/usr/bin/ld: /tmp/cc6hpoSz.o: in function `processBBframe(unsigned char*, unsigned int)':
bbfudpdecap.cpp:(.text+0x25f): undefined reference to `operator delete[](void*)'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0x281): undefined reference to `operator new[](unsigned long)'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0x561): undefined reference to `operator delete[](void*)'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0x76c): undefined reference to `std::ostream::write(char const*, long)'
/usr/bin/ld: /tmp/cc6hpoSz.o: in function `main':
bbfudpdecap.cpp:(.text+0xb2a): undefined reference to `std::cin'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xb38): undefined reference to `std::cout'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xb54): undefined reference to `operator new[](unsigned long)'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xb9a): undefined reference to `std::istream::peek()'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xbc6): undefined reference to `std::istream::read(char*, long)'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xbe6): undefined reference to `std::istream::read(char*, long)'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xc09): undefined reference to `std::basic_ios<char, std::char_traits<char> >::fail() const'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xc2b): undefined reference to `std::istream::peek()'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xc55): undefined reference to `std::istream::read(char*, long)'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xc78): undefined reference to `std::basic_ios<char, std::char_traits<char> >::fail() const'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xcca): undefined reference to `std::istream::read(char*, long)'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xced): undefined reference to `std::basic_ios<char, std::char_traits<char> >::fail() const'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xdf3): undefined reference to `std::basic_ios<char, std::char_traits<char> >::fail() const'
/usr/bin/ld: /tmp/cc6hpoSz.o: in function `__static_initialization_and_destruction_0(int, int)':
bbfudpdecap.cpp:(.text+0xe54): undefined reference to `std::ios_base::Init::Init()'
/usr/bin/ld: bbfudpdecap.cpp:(.text+0xe6f): undefined reference to `std::ios_base::Init::~Init()'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make: *** [Makefile:7: bbfudpdecap] Fehler 1
make: Das Ziel „all“ wurde wegen Fehlern nicht aktualisiert.
```

**Comment by andimik** [comment]
Seems replacing `size` by another expression like `tssize` fixes it:

```
diff --git a/pts2bbf.cpp b/pts2bbf.cpp
index 7fe91b5..088d526 100644
--- a/pts2bbf.cpp
+++ b/pts2bbf.cpp
@@ -7,18 +7,18 @@ using namespace std;
 
 istream* inbuf;
 ostream* outbuf;
-int size;
+int tssize;
 
 int main(int argc, char** argv) {
 	inbuf = &cin;
 	outbuf = &cout;
-	size=200;
-	char* packets= new char[size*188];
+	tssize=200;
+	char* packets= new char[tssize*188];
 	while(1) {
-		inbuf->read(packets,size * 188);
+		inbuf->read(packets,tssize * 188);
 		if(inbuf->fail()) break;
 		unsigned char *p;
-		for(int i=0; i<size*188;i+=188) {
+		for(int i=0; i<tssize*188;i+=188) {
 			int pid=(unsigned char)(packets[i+1]);
 			pid&=0x01F;
 			pid<<=8;

```

But maybe one of these commands helped here, but no idea why it works now:

```
  223  cd apps/bbframe-tools/
  224  make
  225  make CC=gcc-9
  226  make CC=gcc-9 bbfudpdecap 
  227  sudo apt-get update && sudo apt-get upgrade
  228  sudo apt-get install c++-9
  229  sudo apt-get autoclean 
  230  sudo apt-get autoremove 
  231  sudo apt-get install c++-9
  232  make CC=gcc-9 pts2bbf 
  233  cd
  234  yum install gcc-c++
  235  sudo apt-get install yum
  236  sudo su -
  237  g++ --print-prog-name=cc1plus
  238  cd apps/bbframe-tools/
  239  ls
  240  gcc bbfudpdecap.cpp 
  241  gcc pts2bbf.cpp 
  242  g++ -Wall -Wextra -Werror -c bbfudpdecap.cpp pts2bbf.cpp 
  243  g++ bbfudpdecap.cpp pts2bbf.cpp 
  244  make bbfudpdecap 
  245  make bbfudpdecap pts2bbf 
  246  make  pts2bbf 
  247  g++ -o pts2bbf pts2bbf.cpp 
  248  ls -l
  249  ./pts2bbf 
  250  dmesg 
  251  sudo dmesg | grep apa
  252  sudo dmesg | grep ada
  253  ls -l
  254  make clean
  255  ls
  256  git stash 
  257  ls
  258  ls -l
  259  make
  260  g++ -o pts2bbf pts2bbf.cpp 
  261  make
  262  ls
  263  make clean
  264  ls
  265  make
```

```
$ make
g++ -o pts2bbf pts2bbf.cpp
g++ -o bbfudpdecap bbfudpdecap.cpp
```

**Comment by deeptho** [comment]
The problem is the "using namespace std;" at the start. This imports std::size()
Best not to do that and instead replace cin with std::cin. Same for cout, istream and ostream

**Comment by andimik** [comment]
@deeptho 
Thanks, I've sent a PR and successfully tested it under Ubuntu 24.04.

```
$ git diff
diff --git a/pts2bbf.cpp b/pts2bbf.cpp
index 7fe91b5..04a4974 100644
--- a/pts2bbf.cpp
+++ b/pts2bbf.cpp
@@ -3,15 +3,15 @@
 #include<string.h>
 #include<stdlib.h>
 
-using namespace std;
+// using namespace std;   // fixes https://github.com/newspaperman/bbframe-tools/issues/4
 
-istream* inbuf;
-ostream* outbuf;
+std::istream* inbuf;
+std::ostream* outbuf;
 int size;
 
 int main(int argc, char** argv) {
-       inbuf = &cin;
-       outbuf = &cout;
+       inbuf = &std::cin;
+       outbuf = &std::cout;
        size=200;
        char* packets= new char[size*188];
        while(1) {
```

and

```
$ make
g++ -o pts2bbf pts2bbf.cpp
g++ -o bbfudpdecap bbfudpdecap.cpp
```
