### PR TITLE
fix compiling issues Ubuntu, autodetection for PIDs 270 or 280

### LINKED ISSUE #4: Cannot compile in Ubuntu 22.04 - error: reference to ‘size’ is ambiguous
In latest Ubuntu 22.04 compilation fails 

```
$ make
g++ -o pts2bbf pts2bbf.cpp
pts2bbf.cpp: In function ‘int main(int, char**)’:
pts2bbf.cpp:15:9: error: reference to ‘size’ is ambiguous
   15 |         size=200;
      |         ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from pts2bbf.cpp:1:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
pts2bbf.cpp:10:5: note:                 ‘int size’
   10 | int size;
      |     ^~~~
pts2bbf.cpp:16:33: error: reference to ‘size’ is ambiguous
   16 |         char* packets= new char[size*188];
      |                                 ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from pts2bbf.cpp:1:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
pts2bbf.cpp:10:5: note:                 ‘int size’
   10 | int size;
      |     ^~~~
pts2bbf.cpp:18:37: error: reference to ‘size’ is ambiguous
   18 |                 inbuf->read(packets,size * 188);
      |                                     ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from pts2bbf.cpp:1:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
pts2bbf.cpp:10:5: note:                 ‘int size’
   10 | int size;
      |     ^~~~
pts2bbf.cpp:21:32: error: reference to ‘size’ is ambiguous
   21 |                 for(int i=0; i<size*188;i+=188) {
      |                                ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from pts2bbf.cpp:1:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
pts2bbf.cpp:10:5: note:                 ‘int size’
   10 | int size;
      |     ^~~~
make: *** [Makefile:10: pts2bbf] Fehler 1
```

```
$ c++ --version
c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### PR DESCRIPTION
**Pull request by andimik**
fixes https://github.com/newspaperman/bbframe-tools/issues/4

### CODE REVIEW

**Comment by andimik** [comment]
@newspaperman 

Any comments?
